!classDefinition: #Falso category: #'Ejercicio 3'!
DenotativeObject subclass: #Falso
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 3'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Falso class' category: #'Ejercicio 3'!
Falso class
	instanceVariableNames: ''!

!Falso class methodsFor: 'as yet unclassified' stamp: 'MA 9/5/2025 00:11:42'!
no
	^Verdadero! !

!Falso class methodsFor: 'as yet unclassified' stamp: 'MA 9/5/2025 00:13:36'!
o: unBooleano
	^unBooleano! !

!Falso class methodsFor: 'as yet unclassified' stamp: 'MA 9/5/2025 00:13:05'!
siFalso: unaAccionARealizarUIgnorar
	^[unaAccionARealizarUIgnorar]! !

!Falso class methodsFor: 'as yet unclassified' stamp: 'MA 9/5/2025 00:12:33'!
siVerdadero: unaAccionARealizarUIgnorar
	^nil! !

!Falso class methodsFor: 'as yet unclassified' stamp: 'MA 9/5/2025 00:13:22'!
y: unBoolenao
	^Falso! !


!classDefinition: #Verdadero category: #'Ejercicio 3'!
DenotativeObject subclass: #Verdadero
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ejercicio 3'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Verdadero class' category: #'Ejercicio 3'!
Verdadero class
	instanceVariableNames: ''!

!Verdadero class methodsFor: 'as yet unclassified' stamp: 'MA 9/5/2025 00:14:02'!
no
	^Falso! !


!Verdadero class methodsFor: 'as yet unclassified' stamp: 'MA 9/5/2025 00:14:02'!
no
	^Falso! !

!Verdadero class methodsFor: '-- all --' stamp: 'MA 9/5/2025 00:14:41'!
o: unBooleano
	^Verdadero! !

!Verdadero class methodsFor: '-- all --' stamp: 'MA 9/5/2025 00:17:03'!
siFalso: unaAccionARealizarUIgnorar
	^nil! !

!Verdadero class methodsFor: '-- all --' stamp: 'MA 9/5/2025 00:16:43'!
siVerdadero: unaAccionARealizarUIgnorar
	^[unaAccionARealizarUIgnorar]! !

!Verdadero class methodsFor: '-- all --' stamp: 'MA 9/5/2025 00:14:24'!
y: unBooleano
	^unBooleano! !
